Refactor password parser script
openwall/john pull request #5320
Opened 2023-06-16 17:44 UTC by tsvenbla

The specific changes include:

1. Introduced the `use strict` pragma to catch potential issues such as misspelled variable names or the use of uninitialized variables.

2. Replaced print with the `say` feature for better readability and to avoid the need to include a newline character explicitly.

3. Made use of the English module to make some Perl special variables more readable.

4. Introduced a subroutine `output_user` to handle user output, improving code organization and maintainability. This also ensures we don't repeat ourselves when we need to output a user, which follows the DRY (Don't Repeat Yourself) principle.

5. Altering the control flow of the script only to output the user when a new user line is encountered improving the script's efficiency. 

6. Added a condition to output `NoPassword` for users without a password or with a placeholder password `*`, to make the output more meaningful.

These changes make the script more readable, maintainable, and efficient, and they also follow modern Perl best practices.

2023-06-26 12:46 UTC, claudioandre-br approved these changes
It is a 2john tool. We should allow more people to use and test it. We trust your testing. 

I'll try to test it (if we have samples in john-samples). If you have goods samples, please create a PR at https://github.com/openwall/john-samples.

2023-06-26 13:12 UTC, solardiz commented
Thank you for the contributions, @tsvenbla!

We prefer commit message title lines that start with component or subsystem names, e.g. `aix2john.pl: Refactor for improved readability and maintainability`. Fix-ups like `Replaced spaces with tabs` shouldn't be separate commits, but force-pushes of the original commit, as long as they revise things within the same PR that isn't merged yet. (OTOH, a similar fix-up of something already merged would in fact need to be a separate commit.)

2023-06-26 13:25 UTC, claudioandre-br commented
> Thank you for the contributions, @tsvenbla!
> 
> We prefer commit message title lines that start with component or subsystem names, e.g. `aix2john.pl: Refactor for improved readability and maintainability`. Fix-ups like `Replaced spaces with tabs` shouldn't be separate commits, [...]

I bet @tsvenbla is using github GUI, I'm afraid we will need to fix it using the `squash` option.

2023-07-10 19:05 UTC, solardiz requested changes

2023-07-10 19:05 UTC, solardiz commented on run/aix2john.pl
> -#  modification, are permitted.
This used to have a copyright statement and license. Now it does not. Please add your copyright statement (only yours if you kept nothing from the original file) and keep the license statement intact.

2023-07-10 19:05 UTC, solardiz commented on run/aix2john.pl
> +#   username:NoPassword
I think `*` should be kept as-is, just like it's seen in traditional `/etc/passwd` files for locked accounts.

As to `NoPassword` for the case of not seeing a `password` line, I'm not sure. I don't really mind, but maybe it's cleaner to use an empty string in place of the password hash in that case.

I don't know how an actual AIX system behaves when that line is missing.

2023-07-10 19:43 UTC, solardiz commented
@stufus You might want to help review/test the `aix2john.pl` rewrite here. Thank you!

2023-07-10 19:45 UTC, solardiz commented
@kholia I couldn't easily find the original script's author - Konrads Smelkovs - on GitHub. The commit looks like this:

```
commit 19a3e1a459ac8835c4b13cf9a379ca59051c0809
Author:     Konrads Smelkovs <konrads.smelkovs@kpmg.co.uk>
AuthorDate: Fri Oct 4 19:14:00 2013 +0530
Commit:     Dhiru Kholia <dhiru@openwall.com>
CommitDate: Fri Oct 4 19:16:01 2013 +0530

    Perl utility to convert AIX's /etc/security/passwd to JtR format
```

There doesn't appear to be a corresponding GitHub pull request, so I guess this went in via Dhiru privately.

2023-08-02 12:19 UTC, closed without merging