Minimum viable nix-shell with opencl support.
openwall/john pull request #5359
Opened 2023-09-22 11:57 UTC by lambdajack

Adding minimum viable `nix-shell` configuration for use in [Nix/Nixos](https://nixos.org/) with opencl support. The shell supports both AMD and Intel opencl implementations

NOTE: John is available directly through the nixos repository (https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/tools/security/john/default.nix#L85) however that implementation does not support opencl and limits custom building.

The following optional libraries/features are enabled in this shell:

```
Memory map (share/page large files) ................ yes
Fork support ....................................... yes
OpenMP support ..................................... yes (not for fast formats)
OpenCL support ..................................... yes
Generic crypt(3) format ............................ yes
OpenSSL (many additional formats) .................. yes
libgmp (PRINCE mode and faster SRP formats) ........ yes
128-bit integer (faster PRINCE mode) ............... yes
libz (7z, pkzip and some other formats) ............ yes
libbz2 (7z and gpg2john bz2 support) ............... yes
libpcap (vncpcap2john and SIPdump) ................. yes
Non-free unrar code (complete RAR support) ......... yes
librexgen (regex mode, see doc/README.librexgen) ... no
OpenMPI support (default disabled) ................. no
Experimental code (default disabled) ............... no
ZTEX USB-FPGA module 1.15y support ................. no

```

`./src/configure` and `make` tested in a `--pure` nix-shell, meaning it should be reproducible on any nixos installation. make compiles with no errors.

`./run/john --test` runs with no errors and expected opencl speeds.

This should serve as a 'good-enough' base for most requirements, while being a simple starting point for more advanced configuration when building in a nix environment.

`shell.nix` placed in the root directory as recommended by this nix wiki.

2023-09-22 12:37 UTC, solardiz requested changes
Hi. Thanks for the contribution! I'm not familiar with Nix, but I'll make some common sense comments.

For the commit message, can you please reformat it (amend and force-push the one commit) so that it has a title line of at most 72 chars, blank line, and then subsequent paragraphs are wrapped at 75 (except for lines that are naturally longer - e.g., long URLs or copy-paste from elsewhere)? Similar style is used on Linux kernel commit messages.

Please also add a `NEWS` file entry. Currently it would be right after this one:

```
- Added krb5tgs-sha1[-opencl] formats for etypes 17 and 18.  [magnum; 2023]
```

Finally, are comments allowed inside the `shell.nix` file? If so, perhaps it should start with a comment explaining what it is, as well as its copyright statement (that you're the copyright holder?) and license - ideally, our usual 0-clause BSD:

```
Redistribution and use in source and binary forms, with or without
modification, are permitted.

There's ABSOLUTELY NO WARRANTY, express or implied.
```

I understand this may be too minor to be copyrightable, but explicitly having it under a permissive license like that shouldn't hurt.

2023-09-22 12:37 UTC, solardiz commented on shell.nix
> +			export LD=$CC
Shouldn't the two `export` lines be at same indentation?

2023-09-22 12:37 UTC, solardiz commented on shell.nix
> +}
Apparently, missing linefeed after the last line - add it?

2023-09-22 13:20 UTC, solardiz commented
> Update indentation in shell.nix

Such fix-ups within a PR should ideally be made as amends and force-pushes of the commit you're fixing, not as more commits added. If you keep adding commits, we'll need to use GitHub's "squash and merge" on this PR, which is non-ideal.

2023-09-22 14:05 UTC, lambdajack commented
I've added the copyright, license and fixed indentation onto just the one commit.

2023-09-22 14:17 UTC, lambdajack commented
I'm finished force pushing typos now I think........

2023-09-22 16:47 UTC, solardiz approved these changes
I still notice minor things, like this:

```
license, copywrite, info added.
```

which doesn't belong to the commit message (it's part of the temporary history within this PR, and makes little sense in one and only final commit message).

But I don't mind merging this as-is.

2023-09-22 19:46 UTC, merged

2024-03-29 11:08 UTC, Nebucatnetzer commented
To make it work with Nvidia add this part to mkShell worked for me.

```
LD_LIBRARY_PATH= pkgs.lib.makeLibraryPath [
    pkgs.ocl-icd
];
```