Fix of the bug with long Oracle passwords and creation of oracle2john.py
openwall/john pull request #5643
Opened 2024-12-30 13:09 UTC by k4amos

https://github.com/openwall/john/issues/5610

2024-12-30 13:20 UTC, solardiz commented
Thanks @k4amos. Can you please separate the two changes here (added tool vs. patched code) into separate commits?

Also, I am really not sure the trivial fix I suggested is correct. This needs further analysis. I wouldn't be surprised if we see ASan failures after you fix the syntax error (add missing comma after the added test vector). But I don't mind you giving this a try.

2024-12-30 13:23 UTC, solardiz commented
Oh, also we have a convention to prefix commit titles with subsystem names, e.g. `o5logon format: Fix the bug with long Oracle passwords`. For newly added subsystems, no need to prefix with their names, but you can use just `Add oracle2john.py`.

@exploide As usual, we'd appreciate your review of the Python script. Thank you! (And we'll need to remember to credit you prominently for all the Python work when we make the next numbered release.)

2024-12-30 16:11 UTC, exploide requested changes
Just added a few comments which concern mostly possible minor improvements.

However, I have two major things for discussion.

1. There already is `pcap2john.py` which iterates through pcap files and outputs various hashes it can extract. In principle, o5logon support could have been added as a new function within `pcap2john.py`. But I see that there is something different, i.e. o5logon seems to assemble information contained within multiple different packets, if I understand the code correctly? Most (but not all) functions in `pcap2john.py` process single packet authentications, hence they don't need to keep state when parsing the next packet. So it might be fine to have this as a separate script?

2. I think the script is not very robust when parsing larger captures which contain more than just the o5logon procedure. Especially the regex searching within the raw data might be prone to false positives and negatives. Imagine a plain HTTP packet where the word PBKDF2 is contained on a web page. The script would immediately exit in its current form. Is o5logon always contained in TNS packets? I don't see scapy having support for this as a layer which would be nice for filter reasons. If we can't find a way to filter relevant packets in a better way, we may at least need to document that the pcap file should only contain the o5logon/TNS stuff for best results.

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +        "\033[91m[Error] Scapy seems to be missing, run 'pip install --user scapy' to install it\033[0m"
This should go to stderr, i.e. add the parameter `file=sys.stderr` to `print`.

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +            f"\033[91m[Error] The PCAP file {filename} does not contain the required fields of o5logon authentification\033[0m"
Should also go to stderr to avoid having this in the hash output file when redirection is used. I would also consider this being a warning (or omit it altogether) because it might be a valid use case to throw this script on a bunch of pcap files containing arbitrary network traffic.

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +        # Format of the hash : $o5logon$ <server's AUTH_SESSKEY> * <AUTH_VFR_DATA> * <AUTH_PASSWORD> * <client's AUTH_SESSKEY>
I'm not familiar with the o5logon protocol and don't know why the client values can be missing. Would it make sense to add a comment explaining the two cases?

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +            "\033[91m[Error] Sorry, PBKDF2 is not (yet) supported by this utility (only o5logon is)\033[0m"
stderr again. But I'm wondering, it is that fatal that the program should exit? What if another connection is contained within the pcap? And the script seems to support multiple files as well. If the first cannot be processed, the latter will never be tried?

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +        return match_hexa.group(1)
explicitly `return None` otherwise to make the intention clear

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +    parser.add_argument("-f", "--file", type=str, required=True, nargs="+")
Since files are a mandatory and the only parameter the script expects, I would personally omit the flag-style option and just make it a positional argument instead. Most other *2john scripts also do it this way (but not all), so this is a matter of preferences.

2024-12-30 16:11 UTC, exploide commented on run/oracle2john.py
> +        auth_data = read_file(args, filename)
`read_file` does not return any `auth_data`, it looks rather like a `process_file`, prints the hash directly and returns nothing.

2024-12-31 01:30 UTC, solardiz commented
One thing I forgot to note - this is significant enough addition that we should have a `doc/NEWS` entry for it. Adding that can be part of this same PR.

2025-01-04 22:15 UTC, magnumripper commented
> 1. There already is `pcap2john.py` which iterates through pcap files and outputs various hashes it can extract. In principle, o5logon support could have been added as a new function within `pcap2john.py`. But I see that there is something different, i.e. o5logon seems to assemble information contained within multiple different packets, if I understand the code correctly? Most (but not all) functions in `pcap2john.py` process single packet authentications, hence they don't need to keep state when parsing the next packet. So it might be fine to have this as a separate script?

Yeah I think so. If we had more manpower we should rewrite pcap2john.py to be more consistent about what external modules are used (it's currently a merge of several disparate utilities) and ideally support multi packet stuff as well.

2025-01-04 23:05 UTC, magnumripper requested changes

2025-01-04 23:05 UTC, magnumripper commented on src/o5logon_fmt_plug.c
> +		if (extra || len < 64 || len % 32 || len > 3 * PLAINTEXT_LENGTH)
I didn't pay attention at first but I now realized I wrote the original line, lol.

I'm pretty sure the `+ 16` was meant to accommodate a full block of padding after a password length of exact multiple of block size. So `+ 16` should be `+ 32` (presuming I just overlooked that hex doubles the length) or better yet there should be parens as in `2 * (PLAINTEXT_LENGTH + 16)`. If we vary `PLAINTEXT_LENGTH` the `len > 2 * (PLAINTEXT_LENGTH + 16)` is more correct than `len > 3 * PLAINTEXT_LENGTH`.

I had a quick glance at the code for possible places we should bump some array or such, and I believe there is:
```diff
diff --git a/src/o5logon_fmt_plug.c b/src/o5logon_fmt_plug.c
index 498f2d6b1..b5af3e887 100644
--- a/src/o5logon_fmt_plug.c
+++ b/src/o5logon_fmt_plug.c
@@ -83,7 +83,7 @@ static struct custom_salt {
 	unsigned char salt[SALT_LENGTH];         /* AUTH_VFR_DATA */
 	unsigned char ct[CIPHERTEXT_LENGTH];     /* Server's AUTH_SESSKEY */
 	unsigned char csk[CIPHERTEXT_LENGTH];    /* Client's AUTH_SESSKEY */
-	unsigned char pw[16 + PLAINTEXT_LENGTH]; /* Client's AUTH_PASSWORD */
+	unsigned char pw[2 * (PLAINTEXT_LENGTH + 16)]; /* Client's AUTH_PASSWORD */
 	int pw_len;                              /* AUTH_PASSWORD length (blocks) */
 } *cur_salt;
 
```

2025-01-04 23:22 UTC, magnumripper commented on src/o5logon_fmt_plug.c
> +		if (extra || len < 64 || len % 32 || len > 3 * PLAINTEXT_LENGTH)
> I had a quick glance at the code for possible places we should bump some array or such, and I believe there is:

...and BTW after that fix, the `valid()` line might be best written as `if (extra || len < 64 || len % 32 || len > sizeof(((struct custom_salt*)0)->pw))`.

2025-01-04 23:51 UTC, magnumripper requested changes
Oh, and you should `chmod +x oracle2john.py`.

Also, thanks a lot for your contribution! While Ettercap is a fine tool, we better not depend on it.

2025-01-05 00:01 UTC, magnumripper commented on run/oracle2john.py
> +    parser.add_argument("-f", "--file", type=str, required=True, nargs="+")
Agreed, the `-f` option should be dropped. Our convention is `whatever2john <file(s)>`, hashes to stdout and anything else to stderr.

> Most other *2john scripts also do it this way (but not all)

Which do not? We should open an issue for that!

2025-01-05 10:15 UTC, exploide commented on run/oracle2john.py
> +    parser.add_argument("-f", "--file", type=str, required=True, nargs="+")
According to my quick search, at least `radius2john.py` and `aix2john.py`.
Should I change these?

2025-01-05 23:31 UTC, magnumripper commented on run/oracle2john.py
> +    parser.add_argument("-f", "--file", type=str, required=True, nargs="+")
That would be terrific 👍

2025-01-18 16:31 UTC, k4amos commented
Hi everyone,

Thank you for your careful review @exploide  and for your comments @magnumripper

O5logon indeed assembles information from different packets. I agree with you that the regex are not super clean, but I couldn't do better with Scapy and with Pyshark, the problem would be the same.

I hope everything is good this time

2025-01-18 17:03 UTC, exploide approved these changes
Looks good, thanks for incorporating the requested changes :)

The only minor point is the executable bit.

2025-01-18 17:03 UTC, exploide commented on run/oracle2john.py
> +# Make the script executable: chmod +x oracle2john.py
I think what @magnumripper meant was to make this script executable before commiting it, so the comment should no longer be necessary after that. (The executable bit is the only file permission attribute tracked by git.) If you take a look in the `run/` folder, you see the other 2john scripts already have that bit set right after checkout.

2025-01-19 21:13 UTC, magnumripper approved these changes

2025-01-20 13:09 UTC, merged